# Generated by Django 5.0.2 on 2024-03-03 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curso',
            name='instrutor',
        ),
        migrations.AddField(
            model_name='aluno',
            name='cursos_comprados',
            field=models.ManyToManyField(blank=True, related_name='alunos_compradores', to='cadastro.curso'),
        ),
        migrations.DeleteModel(
            name='Instrutor',
        ),
    ]
