# Generated by Django 5.0.2 on 2024-03-03 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0002_remove_curso_instrutor_aluno_cursos_comprados_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='duracao',
            field=models.IntegerField(),
        ),
    ]
