# Generated by Django 5.0.2 on 2024-03-04 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0003_alter_curso_duracao'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='vagas_totais',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='curso',
            name='alunos',
            field=models.ManyToManyField(blank=True, to='cadastro.aluno'),
        ),
    ]
