# Generated by Django 5.0.2 on 2024-03-04 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0004_curso_vagas_totais_alter_curso_alunos'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='faturamento',
            field=models.FloatField(default=float),
            preserve_default=False,
        ),
    ]
