# Generated by Django 5.0.2 on 2024-03-04 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0005_curso_faturamento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curso',
            name='alunos',
        ),
        migrations.DeleteModel(
            name='Aluno',
        ),
    ]
